apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers: 
  - name: nginx-secrets
    image: nginx
    ports:
    - containerPort: 80
    # Using env variables to reference secret key value pairs
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: map-key-secret
          key: API_KEY
    # Mounting secret as volume this way secret data will be available as files inside the pod
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
        readOnly: true
  volumes:  
  - name: secret-volume
    secret:
      secretName: map-key-secret